model:
  name: "HeteroGNN"
  fixed_params:
    out_channels: 1
    dropout: 0.2
  optuna_params:
    hidden_channels:
      min: 32
      max: 256
      log: true
    num_layers:
      min: 2
      max: 5
    gnn_aggr:
      choices: ["add", "mean", "max"]
    learning_rate:
      min: 1e-5
      max: 1e-1
      log: true

loss:
  name: "asymmetric"  # Options: "mse", "asymmetric", "huber", "quantile"
  params:
    alpha: 1.5  # For asymmetric loss
    beta: 0.9   # For quantile loss
    delta: 1.0  # For huber loss