training:
  num_epochs: 100
  early_stopping:
    patience: 5
    min_delta: 1e-4
    monitor: "val_loss"
  optuna:
    n_trials: 50
    direction: "minimize"
    learning_rate:
        min: 0.0001
        max: 0.1
        log: true

  
evaluation:
  threshold: 100  # Maximum return threshold
  prediction_limit: 5  # Maximum prediction value
  metrics:
    - "mse"
    - "rmse"
    - "mae"
    - "r2"
    - "direction_accuracy"
    - "profitable_trades"
    - "information_ratio"
    - "correlation"
    - "market_adjusted_return"

data:
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  use_augmentations: true